name: Main Extension Distribution Pipeline
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref || '' }}-${{ github.base_ref || '' }}-${{ github.ref != 'refs/heads/main' || github.sha }}
  cancel-in-progress: true

jobs:
  duckdb-build:
    name: Build extension binaries
    uses: duckdb/extension-ci-tools/.github/workflows/_extension_distribution.yml@main
    with:
      # The duckdb submodule commit, until the ArrowScanFactory API of duckdb#25726 is ported
      duckdb_version: 38c5eebcb09d8d315fdd2875e778d710ebd5f9d1
      ci_tools_version: main
      extension_name: nanoarrow
