name: NodeJS

on: [push, pull_request, repository_dispatch, workflow_dispatch]

defaults:
  run:
    shell: bash

jobs:
  nodejs:
    name: NodeJS
    runs-on: macos-latest
    env:
      GEN: ninja

    steps:
      - name: Install Ninja
        run: brew install ninja

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: 'true'

      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install required node packages
        run: |
          npm install @duckdb/node-api@1.5.5-r.4 apache-arrow mocha --no-audit --no-fund
          echo "$(pwd)/node_modules/.bin" >> $GITHUB_PATH
          npm -v
          node -v

      - name: Build duckdb
        run: |
          cd duckdb
          git fetch --tags
          git checkout v1.5.5
          cd ..
          GEN=ninja make release

      - name: Run JS tests
        run: |
          make test_release_js
